snowsql_config_path = "~/.snowsql/config"
snowsql_connection_name = "dev"

[default]
input_parameters = "()"
return_type = "string"
file = "app.zip"
name = "avocet_prod_detail_sp"
handler = "app.main"
execute_as_caller = true

[dev]
database = "CANLIN"
schema = "HARMONIZED"
warehouse = "CDE_WH"
role = "CDE_ROLE"
overwrite = true
