snowsql_config_path = "~/.snowsql/config"
snowsql_connection_name = "dev"

[default]
input_parameters = "(alloc_m3 float, gross_m3 float, work_interest float)"
return_type = "float"
file = "app.zip"
name = "gross_to_sales_liquids_udf"
handler = "app.main"
execute_as_caller = true

[dev]
database = "CANLIN"
schema = "HARMONIZED"
warehouse = "CDE_WH"
role = "CDE_ROLE"
overwrite = true
