import sys

def main(area: str) -> str:

    mapping = {'WILSON CRK': 'GILBY', 'COMMOTION': 'FT ST JOHN', 'TURNER VAL': 'WILDCAT HL', 'MINN BL UN': 'GILBY', 'MHCU1': 'MED HAT 1', 'VALE': 'MED HAT 2', 'BLACKSTONE': 'HANLAN', 'MED LODGE': 'HANLAN', 'SHAW': 'HANLAN', 'GWILLIM': 'FT ST JOHN', 'CRANE LK': 'SOUTHSASK', 'BLACKBUTTE': 'MINORSOUTH', 'PEMBINA': 'MINORNORTH', 'CORDEL': 'NORDEGG', 'LAPRISE': 'FT ST JOHN', 'BANSHEE': 'HANLAN', 'WATELET': 'WATELET', 'MTN PARK': 'HANLAN', 'GILBY': 'GILBY', 'CABIN': 'FT NELSON', 'BOUGIE': 'FT ST JOHN', 'HILDA': 'HILDA', 'STOLBERG': 'NORDEGG', 'GLACIER': 'GR PRAIRIE', 'HUNTER VAL': 'HUNTER VAL', 'BURNT TIMB': 'BURNT TIMB', 'MINFTSTJHN': 'FT ST JOHN', 'P1P2': 'MED HAT 1', 'REILLY': 'NORDEGG', 'MEDALLION': 'MEDALLION', 'MUSKIKI': 'NORDEGG', 'BIGSTICK': 'SOUTHSASK', 'MILO': 'FT NELSON', 'VIKING': 'WILDCAT HL', 'PARKLAND': 'GR PRAIRIE', 'KLUA': 'FT NELSON', 'HANLANNOUN': 'HANLAN', 'GRANLEA': 'MINORSOUTH', 'BROWN CRK': 'NORDEGG', 'GHOST RIV': 'WILDCAT HL', 'DROWNINGFD': 'MED HAT 2', 'BIRCH': 'MINORNORTH', 'SCHULER': 'MED HAT 2', 'BOUNDARY': 'FT ST JOHN', 'YOYO': 'FT NELSON', 'PANTHER': 'PANTHER', 'THORSBY': 'MINORNORTH', 'REDCAP': 'HANLAN', 'PECO': 'PECO', 'CAROLINE': 'PANTHER', 'BASING': 'HANLAN', 'CLARKE LK': 'FT NELSON', 'FERRIERNC': 'FERRIER', 'WCH UNIT': 'WILDCAT HL', 'ALDERSON': 'ALDERSON', 'CHANNEL LK': 'MED HAT 2', 'STOLBERGUN': 'NORDEGG', 'FERRIER': 'FERRIER', 'BENJAMIN': 'WILDCAT HL', 'VOYAGER': 'HANLAN', 'HANLANUN': 'HANLAN', 'BURSTALL': 'MED HAT 2', 'MINFTNELSN': 'FT NELSON', 'WOLVERINE': 'FT ST JOHN', 'SWBRNTTIMB': 'BURNT TIMB', 'NESTOW': 'MINORNORTH', 'MINGRPRAIR': 'GR PRAIRIE', 'OJAY': 'FT ST JOHN', None: None, 'ARCHER': 'FT NELSON'}
    
    mapping['BASHAW'] = 'BASHAW'
    
    return mapping[area]


# For local debugging
# Be aware you may need to type-convert arguments if you add input parameters
if __name__ == '__main__':
    if len(sys.argv) > 1:
        print(main(*sys.argv[1:]))  # type: ignore
    else:
        print(main())  # type: ignore
